/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MacDuyKhanh_2018601313;

import javax.swing.JLabel;

/**
 *
 * @author LLoyy
 */
public final class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */ 

 private String hoten;
    private String loai;
    private String km;

    public JLabel getLb_tien() {
        tinh();
        return lb_tien;
    }

    public void setLb_tien(JLabel lb_tien) {
        this.lb_tien = lb_tien;
    }
    

 

   public NewJFrame1(String ten,String km, String loai) {
        initComponents();
        this.km=km;
        this.loai=loai;
        this.lb_ten.setText(ten);
        this.lb_loaikhach.setText(loai);
        this.lb_km.setText(km);
       
      
      
         
    }
   String s;
   String v ="VIP";
    double tt1=0;
    public NewJFrame1() {
        initComponents();
       this.lb_ten.setText(NewJFrame.ten);
       this.lb_km.setText(NewJFrame.km);
       this.lb_loaikhach.setText(NewJFrame.loai);
        if(NewJFrame.loai.equals(v)==true)
        {
            tt1=tienx()-((tienx()*10)/100);
            s=String.valueOf(tt1);
           this.lb_tien.setText(s);
        }else{
            this.lb_tien.setText(String.valueOf(tienx()));
        }
           
    }

     public static Double tienx()
    {
         int km1= Integer.parseInt(NewJFrame.km);
        double tt;
        double tt1=0;
        String s;
        if(km1<1)
        {
           tt=10000;
           return tt;
        }else if(km1>=1 && km1<30)
        {
            tt= km1*9000;
             return tt;
        }else if(km1>=30)
        {
            tt=km1*8000;
             return tt;
        }else return 0.0;
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_ten = new javax.swing.JLabel();
        lb_km = new javax.swing.JLabel();
        lb_loaikhach = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_tien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ten");

        jLabel2.setText("So km");

        jLabel3.setText("Loai khach");

        lb_ten.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lb_tenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel7.setText("Tien:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_km, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_loaikhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(250, 250, 250))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(lb_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lb_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lb_km, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lb_loaikhach, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_tenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lb_tenAncestorAdded
            // TODO add your handling code here:
    }//GEN-LAST:event_lb_tenAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }
    public void tinh()
    {
      int km1= Integer.parseInt(km);
        double tt=0;
        String sh;
        if(km1<1)
        {
           tt=10000;
           
        }else if(km1>1 && km1<30)
        {
            tt= km1*9000;
           
        }else if(km1>=30)
        {
            tt=km1*8000;
            
        }
        
        if(loai.equalsIgnoreCase("VIP"))
        {
           tt=(tt*10)/100;
           sh=String.valueOf(tt);
        }else  sh=String.valueOf(tt);
          
    }
    public Double tinhtien()
    {
        int km1= Integer.parseInt(km);
        double tt=0;
        
        if(km1<1)
        {
           tt=10000;
        }else if(km1>1 && km1<30)
        {
            tt= km1*9000;
        }else if(km1>=30)
        {
            tt=km1*8000;
        }
        
        if(loai.equalsIgnoreCase("VIP"))
        {
           return (tt*10)/100;
        }else return tt;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_km;
    private javax.swing.JLabel lb_loaikhach;
    private javax.swing.JLabel lb_ten;
    private javax.swing.JLabel lb_tien;
    // End of variables declaration//GEN-END:variables
}
